"""RoofSpan Office version/build resolution for support diagnostics.

``windows/VERSION`` remains the release version source of truth. The frozen Windows backend also
receives ``ROOFSPAN_BUILD_SHA`` through a PyInstaller runtime hook generated by ``build_exes.ps1`` so a
customer log/API response can be tied to the exact source commit used for that installer.
"""
import os
import re
from pathlib import Path

_SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+$")
_SHA_RE = re.compile(r"^[0-9a-fA-F]{7,40}$")
_FALLBACK = "0.1.0"


def _read_version() -> str:
    env_v = os.environ.get("ROOFSPAN_VERSION", "").strip()
    if _SEMVER_RE.match(env_v):
        return env_v
    version_file = Path(__file__).resolve().parent.parent / "windows" / "VERSION"
    try:
        file_v = version_file.read_text().strip()
        if _SEMVER_RE.match(file_v):
            return file_v
    except OSError:
        pass
    return _FALLBACK


def _read_build_sha() -> str:
    value = os.environ.get("ROOFSPAN_BUILD_SHA", "").strip()
    return value.lower() if _SHA_RE.fullmatch(value) else "development"


ROOFSPAN_VERSION = _read_version()
CHANNEL = os.environ.get("ROOFSPAN_CHANNEL", "dev")
DISPLAY_VERSION = ROOFSPAN_VERSION if CHANNEL == "stable" else f"{ROOFSPAN_VERSION}-{CHANNEL}"
BUILD_SHA = _read_build_sha()
