"""c3 subscription billing fields

Revision ID: 0b067e6d75cc
Revises: c716e38cdfa3
Create Date: 2026-08-09 22:00:46.016124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b067e6d75cc'
down_revision: Union[str, None] = 'c716e38cdfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('pending_seats', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('pending_seats_effective_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('grace_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'grace_started_at')
    op.drop_column('subscriptions', 'pending_seats_effective_at')
    op.drop_column('subscriptions', 'pending_seats')
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    # ### end Alembic commands ###
