"""c1 control plane baseline

Revision ID: 5263a6bf173f
Revises: 
Create Date: 2026-08-09 20:56:59.953918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5263a6bf173f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cp_audit_logs_action'), 'cp_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_cp_audit_logs_timestamp'), 'cp_audit_logs', ['timestamp'], unique=False)
    op.create_table('entitlement_issuances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('kid', sa.String(length=64), nullable=False),
    sa.Column('subscription_state', sa.String(length=16), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlement_issuances_installation_id'), 'entitlement_issuances', ['installation_id'], unique=False)
    op.create_table('request_nonces',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('signing_keys',
    sa.Column('kid', sa.String(length=64), nullable=False),
    sa.Column('public_pem', sa.Text(), nullable=False),
    sa.Column('private_pem', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('kid')
    )
    op.create_table('version_policy',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('office_latest', sa.String(length=32), nullable=False),
    sa.Column('office_min_supported', sa.String(length=32), nullable=False),
    sa.Column('office_recommended', sa.String(length=32), nullable=False),
    sa.Column('mobile_latest', sa.String(length=32), nullable=False),
    sa.Column('mobile_min_supported', sa.String(length=32), nullable=False),
    sa.Column('mobile_recommended', sa.String(length=32), nullable=False),
    sa.Column('office_update_mandatory', sa.Boolean(), nullable=False),
    sa.Column('mobile_update_mandatory', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('software_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installations_company_id'), 'installations', ['company_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=True),
    sa.Column('product', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_company_id'), 'licenses', ['company_id'], unique=False)
    op.create_index(op.f('ix_licenses_installation_id'), 'licenses', ['installation_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=128), nullable=True),
    sa.Column('renewal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_company_id'), 'subscriptions', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_company_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_licenses_installation_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_company_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_installations_company_id'), table_name='installations')
    op.drop_table('installations')
    op.drop_table('version_policy')
    op.drop_table('signing_keys')
    op.drop_table('request_nonces')
    op.drop_index(op.f('ix_entitlement_issuances_installation_id'), table_name='entitlement_issuances')
    op.drop_table('entitlement_issuances')
    op.drop_index(op.f('ix_cp_audit_logs_timestamp'), table_name='cp_audit_logs')
    op.drop_index(op.f('ix_cp_audit_logs_action'), table_name='cp_audit_logs')
    op.drop_table('cp_audit_logs')
    op.drop_table('companies')
    # ### end Alembic commands ###
