"""c3 pairing tables

Revision ID: 8d6a0d7b8949
Revises: 0b067e6d75cc
Create Date: 2026-08-09 22:09:17.333754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6a0d7b8949'
down_revision: Union[str, None] = '0b067e6d75cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_devices_installation_id'), 'mobile_devices', ['installation_id'], unique=False)
    op.create_table('pairing_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('numeric_code', sa.String(length=12), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_pairing_tokens_installation_id'), 'pairing_tokens', ['installation_id'], unique=False)
    op.create_index(op.f('ix_pairing_tokens_numeric_code'), 'pairing_tokens', ['numeric_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pairing_tokens_numeric_code'), table_name='pairing_tokens')
    op.drop_index(op.f('ix_pairing_tokens_installation_id'), table_name='pairing_tokens')
    op.drop_table('pairing_tokens')
    op.drop_index(op.f('ix_mobile_devices_installation_id'), table_name='mobile_devices')
    op.drop_table('mobile_devices')
    # ### end Alembic commands ###
