"""c2 billing events

Revision ID: c716e38cdfa3
Revises: 5263a6bf173f
Create Date: 2026-08-09 20:57:46.641675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c716e38cdfa3'
down_revision: Union[str, None] = '5263a6bf173f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_timestamp_ms', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resulting_state', sa.String(length=16), nullable=True),
    sa.Column('company_reference', sa.String(length=128), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_events_event_id'), 'billing_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_billing_events_received_at'), 'billing_events', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_events_received_at'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_event_id'), table_name='billing_events')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
