"""add assigned_user_id to leads and jobs

Revision ID: 53c1a6663c52
Revises: e08723e6501e
Create Date: 2026-08-08 17:46:02.072763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c1a6663c52'
down_revision: Union[str, None] = 'e08723e6501e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('assigned_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_assigned_user_id'), 'jobs', ['assigned_user_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('assigned_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leads_assigned_user_id'), 'leads', ['assigned_user_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_assigned_user_id'), table_name='leads')
    op.drop_column('leads', 'assigned_user_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_assigned_user_id'), table_name='jobs')
    op.drop_column('jobs', 'assigned_user_id')
    # ### end Alembic commands ###
