"""phase5 hardening: unique material name

Revision ID: 7a95fb788bfd
Revises: 61f7ea11c757
Create Date: 2026-08-08 05:15:48.433357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a95fb788bfd'
down_revision: Union[str, None] = '61f7ea11c757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_materials_name', 'materials', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_materials_name', 'materials', type_='unique')
    # ### end Alembic commands ###
