"""mobile: photos table

Revision ID: e08723e6501e
Revises: 7a95fb788bfd
Create Date: 2026-08-08 06:19:32.347733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08723e6501e'
down_revision: Union[str, None] = '7a95fb788bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_path', sa.String(length=400), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_created_at'), 'photos', ['created_at'], unique=False)
    op.create_index(op.f('ix_photos_record_id'), 'photos', ['record_id'], unique=False)
    op.create_index(op.f('ix_photos_record_type'), 'photos', ['record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_record_type'), table_name='photos')
    op.drop_index(op.f('ix_photos_record_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_created_at'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
